Repository UMC-7-FIT-PASS/Fitpass-server, pull requests merged in 2025-04, with the labels that each got.

#210 🐛 [Bug] 코인 개수 오류 수정
  src/main/java/com/example/fitpassserver/domain/coin/service/CoinService.java
Labels: 🐛bug

#214 🐛[Fix]: 홈슬라이드 공지 이미지 조회 API 수정
  src/main/java/com/example/fitpassserver/domain/notice/controller/NoticeController.java
  src/main/java/com/example/fitpassserver/domain/notice/service/NoticeService.java
Labels: 🐛bug

#217 🐛 [Fix] CoinPaymentHistory 코인 개수 수정
  src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/CoinPaymentHistoryService.java
Labels: 🐛bug

#211 ✨ [Feature] 업체 대시보드 API
  src/main/java/com/example/fitpassserver/admin/notice/controller/NoticeAdminController.java
  src/main/java/com/example/fitpassserver/admin/notice/service/NoticeAdminService.java
  src/main/java/com/example/fitpassserver/admin/notice/service/NoticeAdminServiceImpl.java
  src/main/java/com/example/fitpassserver/owner/dashboard/controller/DashboardOwnerController.java
  src/main/java/com/example/fitpassserver/owner/dashboard/service/DashboardOwnerService.java
  src/main/java/com/example/fitpassserver/owner/dashboard/service/DashboardOwnerServiceImpl.java
Labels: ♻️refactor, ✨feature

#222 ✨ [Feat] PG사 API 연결 정기 결제 제외
  src/main/java/com/example/fitpassserver/domain/coin/service/CoinService.java
  src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/controller/CoinPaymentController.java
  src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/dto/request/PGRequestDTO.java
  src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/dto/request/PortOneRequestDTO.java
  src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/dto/response/PGResponseDTO.java
  src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/dto/response/PortOneResponseDTO.java
  src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/exception/PortOneErrorCode.java
  src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/exception/PortOneException.java
  src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/listener/CoinPaymentEventListener.java
  src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/CoinPaymentHistoryService.java
  src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/command/PGPaymentCommandService.java
  src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/command/PGPaymentCommandServiceImpl.java
  src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/query/PGPaymentQueryService.java
  src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/query/PGPaymentQueryServiceImpl.java
  src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/util/PortOneApiUtil.java
Labels: ✨feature

#227 [Fix] 사업자 회원가입
  src/main/java/com/example/fitpassserver/domain/fitness/entity/Fitness.java
  src/main/java/com/example/fitpassserver/global/common/dto/CommonResponseDTO.java
  src/main/java/com/example/fitpassserver/global/common/service/CommonServiceImpl.java
  src/main/java/com/example/fitpassserver/owner/owner/converter/OwnerConverter.java
  src/main/java/com/example/fitpassserver/owner/owner/entity/Owner.java
  src/main/java/com/example/fitpassserver/owner/owner/service/command/OwnerCommandServiceImpl.java
Labels: 🐛bug

#232 🐛 [Fix] @CurrentOwner로 변경
  src/main/java/com/example/fitpassserver/owner/dashboard/controller/DashboardOwnerController.java
  src/main/java/com/example/fitpassserver/owner/dashboard/service/DashboardOwnerService.java
  src/main/java/com/example/fitpassserver/owner/dashboard/service/DashboardOwnerServiceImpl.java
  src/main/java/com/example/fitpassserver/owner/notice/controller/NoticeOwnerController.java
  src/main/java/com/example/fitpassserver/owner/notice/service/NoticeOwnerService.java
  src/main/java/com/example/fitpassserver/owner/notice/service/NoticeOwnerServiceImpl.java
  src/main/java/com/example/fitpassserver/owner/owner/controller/OwnerController.java
Labels: 🐛bug

#234 ♻️ [Refactor] 알림톡 구현
  src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/listener/CoinPaymentEventListener.java
  src/main/java/com/example/fitpassserver/domain/fitness/service/MemberFitnessService.java
  src/main/java/com/example/fitpassserver/domain/fitness/service/command/MemberFitnessCommandServiceImpl.java
  src/main/java/com/example/fitpassserver/domain/kakaoNotice/template/AlimtalkTemplate.java
  src/main/java/com/example/fitpassserver/domain/kakaoNotice/util/KakaoAlimtalkUtil.java
  src/main/java/com/example/fitpassserver/domain/member/service/command/MemberCommandServiceImpl.java
  src/main/java/com/example/fitpassserver/domain/plan/dto/event/PlanChangeAllSuccessEvent.java
  src/main/java/com/example/fitpassserver/domain/plan/listener/PlanSubscriptionEventListener.java
  src/main/java/com/example/fitpassserver/domain/plan/service/PlanScheduler.java
  src/main/java/com/example/fitpassserver/domain/plan/service/PlanService.java
  src/main/java/com/example/fitpassserver/domain/review/entity/ReviewNotification.java
  src/main/java/com/example/fitpassserver/domain/review/repsotiory/ReviewNotificationRepository.java
  src/main/java/com/example/fitpassserver/domain/review/scheduler/ReviewNotificationScheduler.java
  src/main/java/com/example/fitpassserver/domain/review/service/ReviewReminderService.java
  src/main/java/com/example/fitpassserver/global/config/RestTemplateConfig.java
Labels: ♻️refactor, ✨feature

#235 ✨ [Feat] PG사 정기결제 API 구현
  src/main/java/com/example/fitpassserver/domain/coin/service/CoinService.java
  src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/controller/CoinPaymentController.java
  src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/dto/request/PGRequestDTO.java
  src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/dto/response/PGResponseDTO.java
  src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/CoinPaymentHistoryService.java
  src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/command/PGPaymentCommandService.java
  src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/command/PGPaymentCommandServiceImpl.java
  src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/util/PortOneApiUtil.java
  src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/util/PortOnePaymentIdUtil.java
  src/main/java/com/example/fitpassserver/domain/plan/controller/PlanPaymentController.java
  src/main/java/com/example/fitpassserver/domain/plan/entity/PaymentType.java
  src/main/java/com/example/fitpassserver/domain/plan/entity/Plan.java
  src/main/java/com/example/fitpassserver/domain/plan/listener/PlanSubscriptionEventListener.java
  src/main/java/com/example/fitpassserver/domain/plan/service/PlanScheduler.java
  src/main/java/com/example/fitpassserver/domain/plan/service/PlanService.java
Labels: ✨feature

#238 🐛 [Fix] 카드 목록 가져오기 Http method 변경
  src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/controller/CoinPaymentController.java
Labels: 🐛bug

#241 ♻️ [Refactor] 위치동의 팝업 api 수정
  src/main/java/com/example/fitpassserver/domain/member/controller/MemberController.java
  src/main/java/com/example/fitpassserver/domain/member/dto/MemberRequestDTO.java
  src/main/java/com/example/fitpassserver/domain/member/service/command/MemberCommandService.java
  src/main/java/com/example/fitpassserver/domain/member/service/command/MemberCommandServiceImpl.java
Labels: ♻️refactor

#244 :recycle: [Refactor[ 로그인시 ownerId, ownerName 반환
  src/main/java/com/example/fitpassserver/global/common/service/CommonServiceImpl.java
Labels: ♻️refactor

#250 ♻️ [Refactor] 무중단 배포
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/com/example/fitpassserver/global/config/SecurityConfig.java
Labels: ♻️refactor

#252 ♻️ [Refactor] 로컬 Nginx 사용
  .github/workflows/deploy.yml
Labels: ♻️refactor

#253 ♻️ [Refactor] 공지사항 리팩토링
  src/main/java/com/example/fitpassserver/admin/notice/controller/NoticeAdminController.java
  src/main/java/com/example/fitpassserver/admin/notice/converter/NoticeAdminConverter.java
  src/main/java/com/example/fitpassserver/admin/notice/dto/request/NoticeAdminReqDTO.java
  src/main/java/com/example/fitpassserver/admin/notice/dto/response/NoticeAdminResDTO.java
  src/main/java/com/example/fitpassserver/admin/notice/service/NoticeAdminServiceImpl.java
  src/main/java/com/example/fitpassserver/domain/notice/entity/Notice.java
  src/main/java/com/example/fitpassserver/domain/notice/repository/NoticeRepository.java
  src/main/java/com/example/fitpassserver/owner/notice/service/NoticeOwnerServiceImpl.java
Labels: ♻️refactor

#254 ✨ [Feature] 시설회원 어드민 기능 추가
  src/main/java/com/example/fitpassserver/admin/owner/controller/OwnerAdminController.java
  src/main/java/com/example/fitpassserver/admin/owner/converter/OwnerAdminConverter.java
  src/main/java/com/example/fitpassserver/admin/owner/dto/OwnerAdminResponseDTO.java
  src/main/java/com/example/fitpassserver/admin/owner/service/command/OwnerAdminCommandService.java
  src/main/java/com/example/fitpassserver/admin/owner/service/command/OwnerAdminCommandServiceImpl.java
  src/main/java/com/example/fitpassserver/admin/owner/service/query/OwnerAdminQueryService.java
  src/main/java/com/example/fitpassserver/admin/owner/service/query/OwnerAdminQueryServiceImpl.java
  src/main/java/com/example/fitpassserver/owner/owner/entity/Owner.java
  src/main/java/com/example/fitpassserver/owner/owner/entity/OwnerStatus.java
  src/main/java/com/example/fitpassserver/owner/owner/repository/OwnerRepository.java
Labels: ✨feature

#256 :recycle: [Refactor] 회원가입 인증코드 카톡 발송으로 변경
  src/main/java/com/example/fitpassserver/domain/kakaoNotice/template/AlimtalkTemplate.java
  src/main/java/com/example/fitpassserver/domain/kakaoNotice/util/KakaoAlimtalkUtil.java
  src/main/java/com/example/fitpassserver/domain/member/sms/service/SmsServiceImpl.java
Labels: ♻️refactor

#262 :rocket: [Chore] Swagger 회원별 정리
  src/main/java/com/example/fitpassserver/admin/member/controller/MemberAdminController.java
  src/main/java/com/example/fitpassserver/domain/profile/controller/ProfileController.java
  src/main/java/com/example/fitpassserver/global/config/SwaggerConfig.java
  src/main/java/com/example/fitpassserver/owner/fitnessHistory/controller/FitnessHistoryController.java
  src/main/java/com/example/fitpassserver/owner/owner/controller/OwnerController.java
Labels: 🚀chore

#270 :sparkles: [Feat]: 어드민 시설 단일 조회 API
  src/main/java/com/example/fitpassserver/admin/fitness/controller/FitnessAdminController.java
  src/main/java/com/example/fitpassserver/admin/fitness/converter/FitnessAdminConverter.java
  src/main/java/com/example/fitpassserver/admin/fitness/dto/response/FitnessAdminResponseDTO.java
  src/main/java/com/example/fitpassserver/admin/fitness/service/FitnessAdminService.java
  src/main/java/com/example/fitpassserver/admin/fitness/service/FitnessAdminServiceImpl.java
Labels: ✨feature

#267 ✨ [Feat] 리뷰 작성 시 코인 지급
  src/main/java/com/example/fitpassserver/domain/coin/service/CoinService.java
  src/main/java/com/example/fitpassserver/domain/review/service/ReviewService.java
Labels: ✨feature
