Repository UMC-7-FIT-PASS/Fitpass-server, pull requests merged in 2025-02, with the labels that each got.

#114 🐛 [Fix] 피트니스 구매 조건 수정
  src/main/java/com/example/fitpassserver/domain/fitness/repository/MemberFitnessRepository.java
  src/main/java/com/example/fitpassserver/domain/fitness/service/command/MemberFitnessCommandServiceImpl.java
Labels: 🐛bug

#115 ♻️ refactor(memberfitness) 보유 패스 조회 시설 사진 추가
  src/main/java/com/example/fitpassserver/domain/fitness/converter/MemberFitnessConverter.java
  src/main/java/com/example/fitpassserver/domain/fitness/dto/response/MemberFitnessResDTO.java
  src/main/java/com/example/fitpassserver/domain/fitness/service/MemberFitnessService.java
Labels: ♻️refactor

#118 ♻️ refactor(memberfitness) dto 변수명 수정
  src/main/java/com/example/fitpassserver/domain/fitness/controller/response/FitnessPaymentResponse.java
  src/main/java/com/example/fitpassserver/domain/fitness/controller/response/FitnessRecommendResponse.java
  src/main/java/com/example/fitpassserver/domain/fitness/converter/MemberFitnessConverter.java
  src/main/java/com/example/fitpassserver/domain/fitness/dto/response/MemberFitnessResDTO.java
  src/main/java/com/example/fitpassserver/domain/fitness/service/FitnessRecommendService.java
Labels: ♻️refactor

#129 ♻️ [Refactor] 패스 상태 추가
  src/main/java/com/example/fitpassserver/domain/fitness/converter/MemberFitnessConverter.java
  src/main/java/com/example/fitpassserver/domain/fitness/dto/response/MemberFitnessResDTO.java
  src/main/java/com/example/fitpassserver/domain/fitness/entity/MemberFitness.java
  src/main/java/com/example/fitpassserver/domain/fitness/entity/Status.java
  src/main/java/com/example/fitpassserver/domain/review/service/ReviewService.java
Labels: ♻️refactor

#132 ✨ [Feat] 어드민 사용자 조회 기능
  src/main/java/com/example/fitpassserver/admin/member/controller/MemberAdminController.java
  src/main/java/com/example/fitpassserver/admin/member/converter/MemberAdminConverter.java
  src/main/java/com/example/fitpassserver/admin/member/dto/response/MemberAdminResponseDTO.java
  src/main/java/com/example/fitpassserver/admin/member/service/MemberAdminService.java
  src/main/java/com/example/fitpassserver/admin/member/service/MemberAdminServiceImpl.java
  src/main/java/com/example/fitpassserver/domain/member/entity/Member.java
  src/main/java/com/example/fitpassserver/domain/member/principal/CustomOAuth2UserService.java
  src/main/java/com/example/fitpassserver/domain/member/repository/MemberRepository.java
  src/main/java/com/example/fitpassserver/domain/member/service/command/MemberCommandServiceImpl.java
  src/main/java/com/example/fitpassserver/global/oauth/handler/CustomOAuth2SuccessHandler.java
Labels: ✨feature

#127 ✨ [Feat] 피트니스 어드민
  src/main/java/com/example/fitpassserver/admin/fitness/controller/FitnessAdminController.java
  src/main/java/com/example/fitpassserver/admin/fitness/converter/FitnessAdminConverter.java
  src/main/java/com/example/fitpassserver/admin/fitness/dto/request/FitnessAdminRequestDTO.java
  src/main/java/com/example/fitpassserver/admin/fitness/dto/response/FitnessAdminResponseDTO.java
  src/main/java/com/example/fitpassserver/admin/fitness/service/FitnessAdminService.java
  src/main/java/com/example/fitpassserver/admin/fitness/service/FitnessAdminServiceImpl.java
  src/main/java/com/example/fitpassserver/domain/fitness/controller/FitnessController.java
  src/main/java/com/example/fitpassserver/domain/fitness/controller/MemberFitnessController.java
  src/main/java/com/example/fitpassserver/domain/fitness/converter/CategoryConverter.java
  src/main/java/com/example/fitpassserver/domain/fitness/converter/FitnessImageConverter.java
  src/main/java/com/example/fitpassserver/domain/fitness/converter/MemberFitnessConverter.java
  src/main/java/com/example/fitpassserver/domain/fitness/dto/MemberFitnessRequestDTO.java
  src/main/java/com/example/fitpassserver/domain/fitness/entity/Fitness.java
  src/main/java/com/example/fitpassserver/domain/fitness/entity/FitnessImage.java
  src/main/java/com/example/fitpassserver/domain/fitness/repository/FitnessImageRepository.java
  src/main/java/com/example/fitpassserver/domain/fitness/repository/FitnessRepository.java
  src/main/java/com/example/fitpassserver/domain/fitness/repository/MemberFitnessRepository.java
  src/main/java/com/example/fitpassserver/domain/fitness/service/FitnessDetailService.java
  src/main/java/com/example/fitpassserver/domain/fitness/service/FitnessListService.java
  src/main/java/com/example/fitpassserver/domain/fitness/service/FitnessRecommendService.java
  src/main/java/com/example/fitpassserver/domain/fitness/service/MemberFitnessService.java
  src/main/java/com/example/fitpassserver/domain/fitness/util/PassStatusScheduler.java
  src/main/java/com/example/fitpassserver/global/converter/MultipartJackson2HttpMessageConverter.java
Labels: ✨feature

#137 🐛 [Bug] 대시보드 구매 조건 수정
  src/main/java/com/example/fitpassserver/domain/fitness/repository/MemberFitnessRepository.java
  src/main/java/com/example/fitpassserver/domain/fitness/service/command/MemberFitnessCommandServiceImpl.java
Labels: 🐛bug

#141 ✨ [Feat] Admin 대시보드 구현 (페이지 뷰 제외)
  src/main/java/com/example/fitpassserver/admin/dashboard/controller/DashboardAdminController.java
  src/main/java/com/example/fitpassserver/admin/dashboard/converter/DashBoardConverter.java
  src/main/java/com/example/fitpassserver/admin/dashboard/dto/response/DashBoardResponseDTO.java
  src/main/java/com/example/fitpassserver/admin/dashboard/entity/DashBoard.java
  src/main/java/com/example/fitpassserver/admin/dashboard/repository/DashBoardRepository.java
  src/main/java/com/example/fitpassserver/admin/dashboard/service/DashboardAdminService.java
  src/main/java/com/example/fitpassserver/admin/dashboard/service/DashboardAdminServiceImpl.java
  src/main/java/com/example/fitpassserver/admin/dashboard/util/VisitorUtil.java
  src/main/java/com/example/fitpassserver/domain/fitness/repository/MemberFitnessRepository.java
  src/main/java/com/example/fitpassserver/domain/member/repository/MemberRepository.java
  src/main/java/com/example/fitpassserver/global/config/WebConfig.java
  src/main/java/com/example/fitpassserver/global/config/interceptor/VisitorInterceptor.java
Labels: ✨feature

#143 ♻️ refactor(pass) 패스 시설 조회 로직 수정
  src/main/java/com/example/fitpassserver/domain/fitness/converter/MemberFitnessConverter.java
  src/main/java/com/example/fitpassserver/domain/fitness/service/MemberFitnessService.java
Labels: ♻️refactor

#147 ♻️ [Refactor] 소셜 로그인 시 Role 반환 추가, 어드민 회원 정보 Swagger Tag 추가
  src/main/java/com/example/fitpassserver/admin/member/controller/MemberAdminController.java
  src/main/java/com/example/fitpassserver/global/oauth/handler/CustomOAuth2SuccessHandler.java
Labels: ♻️refactor

#151 :recycle: [Refactor] 로그인시 role 반환 및 컨트롤러 tag 추가
  src/main/java/com/example/fitpassserver/domain/member/controller/MemberController.java
  src/main/java/com/example/fitpassserver/domain/member/dto/MemberResponseDTO.java
  src/main/java/com/example/fitpassserver/domain/member/service/command/MemberCommandServiceImpl.java
  src/main/java/com/example/fitpassserver/domain/member/sms/controller/SmsController.java
  src/main/java/com/example/fitpassserver/domain/profile/controller/ProfileController.java
Labels: ♻️refactor

#149 🐛 [Fix] 패스 구매 조건 및 패스 상태 변경 로직 수정
  src/main/java/com/example/fitpassserver/domain/fitness/exception/MemberFitnessErrorCode.java
  src/main/java/com/example/fitpassserver/domain/fitness/repository/MemberFitnessCustomRepository.java
  src/main/java/com/example/fitpassserver/domain/fitness/repository/MemberFitnessCustomRepositoryImpl.java
  src/main/java/com/example/fitpassserver/domain/fitness/repository/MemberFitnessRepository.java
  src/main/java/com/example/fitpassserver/domain/fitness/service/MemberFitnessService.java
  src/main/java/com/example/fitpassserver/domain/fitness/service/command/MemberFitnessCommandServiceImpl.java
  src/main/java/com/example/fitpassserver/domain/fitness/util/PassStatusScheduler.java
Labels: 🐛bug

#153 ✨ [Feat] 페이지 뷰 기능 구현
  src/main/java/com/example/fitpassserver/admin/dashboard/controller/PageViewController.java
  src/main/java/com/example/fitpassserver/admin/dashboard/converter/PageViewConverter.java
  src/main/java/com/example/fitpassserver/admin/dashboard/dto/response/PageViewResponseDTO.java
  src/main/java/com/example/fitpassserver/admin/dashboard/service/DashboardAdminServiceImpl.java
  src/main/java/com/example/fitpassserver/admin/dashboard/util/VisitorUtil.java
  src/main/java/com/example/fitpassserver/global/config/SecurityConfig.java
Labels: ✨feature

#161 :recycle: [Refactor] 어드민 공지사항 수정
  src/main/java/com/example/fitpassserver/admin/notice/controller/NoticeAdminController.java
  src/main/java/com/example/fitpassserver/admin/notice/dto/response/AdminNoticeDetailDTO.java
  src/main/java/com/example/fitpassserver/admin/notice/dto/response/NoticeDraftResDTO.java
  src/main/java/com/example/fitpassserver/admin/notice/service/NoticeAdminService.java
  src/main/java/com/example/fitpassserver/domain/fitness/controller/FitnessController.java
  src/main/java/com/example/fitpassserver/domain/notice/repository/NoticeRepository.java
  src/main/java/com/example/fitpassserver/domain/notice/service/NoticeService.java
Labels: ♻️refactor

#155 :recycle: [Refactor] 피트니스 조회 수정
  src/main/java/com/example/fitpassserver/domain/fitness/controller/response/FitnessDetailResponse.java
  src/main/java/com/example/fitpassserver/domain/fitness/repository/FitnessRepository.java
  src/main/java/com/example/fitpassserver/domain/fitness/service/FitnessDetailService.java
  src/main/java/com/example/fitpassserver/domain/fitness/service/FitnessImageService.java
  src/main/java/com/example/fitpassserver/domain/fitness/service/FitnessListService.java
  src/main/java/com/example/fitpassserver/domain/fitness/service/FitnessSearchService.java
Labels: ♻️refactor

#159 ♻️ [Refactor] 사용자 생성 시 위도 경도 기본값 설정
  src/main/java/com/example/fitpassserver/domain/member/entity/Member.java
Labels: ♻️refactor

#166 ♻️ refactor(fitness) 피트니스 time 저장&응답 수정
  src/main/java/com/example/fitpassserver/admin/fitness/converter/FitnessAdminConverter.java
  src/main/java/com/example/fitpassserver/admin/fitness/dto/request/FitnessAdminRequestDTO.java
  src/main/java/com/example/fitpassserver/admin/fitness/service/FitnessAdminServiceImpl.java
  src/main/java/com/example/fitpassserver/domain/fitness/service/FitnessDetailService.java
Labels: ♻️refactor

#171 :recycle: [Refactor] 구독/코인 요금제 조회 url 변경
  src/main/java/com/example/fitpassserver/admin/management/controller/ManagementAdminController.java
  src/main/java/com/example/fitpassserver/global/config/SecurityConfig.java
Labels: ♻️refactor

#173 ♻️ refactor(fitness) 피트니스 구매 화면 수정
  src/main/java/com/example/fitpassserver/admin/fitness/converter/FitnessAdminConverter.java
  src/main/java/com/example/fitpassserver/domain/fitness/controller/response/FitnessPaymentResponse.java
  src/main/java/com/example/fitpassserver/domain/fitness/exception/FitnessErrorCode.java
Labels: ♻️refactor

#176 🐛 [Fix] 패스 구매 조건 수정
  src/main/java/com/example/fitpassserver/domain/fitness/repository/MemberFitnessRepository.java
  src/main/java/com/example/fitpassserver/domain/fitness/service/command/MemberFitnessCommandServiceImpl.java
Labels: 🐛bug

#179 :recycle: [Refactor] 프로필 이미지 변경 presigned url 로직 추가
  src/main/java/com/example/fitpassserver/domain/profile/controller/ProfileController.java
  src/main/java/com/example/fitpassserver/domain/profile/service/ProfileService.java
  src/main/java/com/example/fitpassserver/global/aws/s3/service/S3Service.java
Labels: ♻️refactor

#186 🐛 [Fix] 패스 구매 제한 임시 해제
  src/main/java/com/example/fitpassserver/domain/fitness/service/command/MemberFitnessCommandServiceImpl.java
Labels: 🐛bug
