Repository UMC-7-FIT-PASS/Fitpass-server, pull requests merged in 2025-03, with the labels that each got.

#192 ♻️ [Refactor] 카카오 알림톡 구현
  src/main/java/com/example/fitpassserver/domain/coin/service/CoinService.java
  src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/dto/event/CoinPaymentAllSuccessEvent.java
  src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/listener/CoinPaymentEventListener.java
  src/main/java/com/example/fitpassserver/domain/fitness/service/command/MemberFitnessCommandServiceImpl.java
  src/main/java/com/example/fitpassserver/domain/kakaoNotice/util/KakaoAlimtalkUtil.java
  src/main/java/com/example/fitpassserver/domain/plan/dto/event/PlanPaymentAllSuccessEvent.java
  src/main/java/com/example/fitpassserver/domain/plan/listener/PlanSubscriptionEventListener.java
  src/main/java/com/example/fitpassserver/domain/plan/service/PlanScheduler.java
  src/main/java/com/example/fitpassserver/domain/plan/service/PlanService.java
Labels: ♻️refactor

#194 :recycle: [Refactor] 회원가입시 위치정보 동의 반환
  src/main/java/com/example/fitpassserver/domain/member/converter/MemberConverter.java
  src/main/java/com/example/fitpassserver/domain/member/dto/MemberRequestDTO.java
  src/main/java/com/example/fitpassserver/domain/member/dto/MemberResponseDTO.java
  src/main/java/com/example/fitpassserver/domain/member/entity/Member.java
  src/main/java/com/example/fitpassserver/domain/member/service/command/MemberCommandServiceImpl.java
Labels: ♻️refactor

#196 🐛 [Fix] 중복 전화번호 임시 허용
  build.gradle
  src/main/java/com/example/fitpassserver/domain/member/service/command/MemberCommandServiceImpl.java
Labels: 🐛bug

#199 :bug: [Fix} 로그인, 회원가입시 위치정보 반환
  src/main/java/com/example/fitpassserver/domain/member/converter/MemberConverter.java
  src/main/java/com/example/fitpassserver/domain/member/dto/MemberResponseDTO.java
  src/main/java/com/example/fitpassserver/domain/member/service/command/MemberCommandServiceImpl.java
Labels: 🐛bug

#203 ♻️ [Refactor] 공지사항 사장님 로직
  src/main/java/com/example/fitpassserver/admin/notice/controller/NoticeAdminController.java
  src/main/java/com/example/fitpassserver/admin/notice/exception/NoticeAdminErrorCode.java
  src/main/java/com/example/fitpassserver/admin/notice/service/NoticeAdminService.java
  src/main/java/com/example/fitpassserver/domain/member/entity/Role.java
  src/main/java/com/example/fitpassserver/domain/notice/controller/NoticeController.java
  src/main/java/com/example/fitpassserver/domain/notice/entity/Notice.java
  src/main/java/com/example/fitpassserver/domain/notice/exception/NoticeErrorCode.java
  src/main/java/com/example/fitpassserver/domain/notice/repository/NoticeRepository.java
  src/main/java/com/example/fitpassserver/domain/notice/service/NoticeService.java
  src/main/java/com/example/fitpassserver/global/config/SecurityConfig.java
  src/main/java/com/example/fitpassserver/owner/notice/controller/NoticeOwnerController.java
  src/main/java/com/example/fitpassserver/owner/notice/service/NoticeOwnerService.java
  src/main/java/com/example/fitpassserver/owner/notice/service/NoticeOwnerServiceImpl.java
Labels: ♻️refactor

#205 ✨ [Feature] 시설 UD 구현
  src/main/java/com/example/fitpassserver/admin/fitness/controller/FitnessAdminController.java
  src/main/java/com/example/fitpassserver/admin/fitness/converter/FitnessAdminConverter.java
  src/main/java/com/example/fitpassserver/admin/fitness/dto/request/FitnessAdminRequestDTO.java
  src/main/java/com/example/fitpassserver/admin/fitness/service/FitnessAdminService.java
  src/main/java/com/example/fitpassserver/admin/fitness/service/FitnessAdminServiceImpl.java
  src/main/java/com/example/fitpassserver/domain/fitness/entity/Fitness.java
Labels: ✨feature

#208 🐛 [Fix] notice 어드민 응답 수정
  src/main/java/com/example/fitpassserver/admin/notice/converter/NoticeAdminConverter.java
  src/main/java/com/example/fitpassserver/admin/notice/dto/response/NoticeAdminResDTO.java
Labels: ♻️refactor
