Repository UMC-7-FIT-PASS/Fitpass-server, pull requests merged in 2025-01, with the labels that each got.

#2 🚀 [Chore] 프로젝트 초기 세팅
  .gitattributes
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/example/fitpassserver/FitpassServerApplication.java
  src/main/java/com/example/fitpassserver/global/apiPayload/ApiResponse.java
  src/main/java/com/example/fitpassserver/global/apiPayload/code/BaseCode.java
  src/main/java/com/example/fitpassserver/global/apiPayload/code/BaseErrorCode.java
  src/main/java/com/example/fitpassserver/global/apiPayload/code/ErrorReasonDTO.java
  src/main/java/com/example/fitpassserver/global/apiPayload/code/ReasonDTO.java
  src/main/java/com/example/fitpassserver/global/apiPayload/code/base/FailureCode.java
  src/main/java/com/example/fitpassserver/global/apiPayload/code/base/SuccessCode.java
  src/main/java/com/example/fitpassserver/global/apiPayload/exception/GeneralException.java
  src/main/java/com/example/fitpassserver/global/apiPayload/exception/base/FailureException.java
  src/main/java/com/example/fitpassserver/global/apiPayload/exception/handler/ExceptionAdvice.java
  src/main/java/com/example/fitpassserver/global/config/SwaggerConfig.java
  src/main/java/com/example/fitpassserver/global/entity/BaseEntity.java
  src/test/java/com/example/fitpassserver/FitpassServerApplicationTests.java
Labels: 🚀chore

#4 :sparkles: feat(entity): 도메인 별 entity 작성
  src/main/java/com/example/fitpassserver/domain/CoinPaymentHistory/entity/CoinPaymentHistory.java
  src/main/java/com/example/fitpassserver/domain/coin/entity/Coin.java
  src/main/java/com/example/fitpassserver/domain/coin/entity/CoinUsageHistory.java
  src/main/java/com/example/fitpassserver/domain/fitness/entity/Category.java
  src/main/java/com/example/fitpassserver/domain/fitness/entity/Fitness.java
  src/main/java/com/example/fitpassserver/domain/fitness/entity/MemberFitness.java
  src/main/java/com/example/fitpassserver/domain/fitness/entity/Status.java
  src/main/java/com/example/fitpassserver/domain/fitnessPaymentHistory/entity/FitnessPaymentHistory.java
  src/main/java/com/example/fitpassserver/domain/member/entity/Member.java
  src/main/java/com/example/fitpassserver/domain/member/entity/Role.java
  src/main/java/com/example/fitpassserver/domain/notice/entity/Notice.java
  src/main/java/com/example/fitpassserver/domain/plan/entity/Plan.java
  src/main/java/com/example/fitpassserver/domain/plan/entity/PlanName.java
  src/main/java/com/example/fitpassserver/domain/review/entity/Review.java
Labels: ✨feature

#11 ✨ [Feat] 리뷰 관련 기능
  src/main/java/com/example/fitpassserver/domain/fitness/entity/exception/FitnessErrorCode.java
  src/main/java/com/example/fitpassserver/domain/fitness/entity/exception/FitnessException.java
  src/main/java/com/example/fitpassserver/domain/fitness/entity/repository/MemberFitnessRepository.java
  src/main/java/com/example/fitpassserver/domain/review/controller/ReviewController.java
  src/main/java/com/example/fitpassserver/domain/review/converter/ReviewConverter.java
  src/main/java/com/example/fitpassserver/domain/review/dto/request/ReviewReqDTO.java
  src/main/java/com/example/fitpassserver/domain/review/dto/response/ReviewResDTO.java
  src/main/java/com/example/fitpassserver/domain/review/entity/Review.java
  src/main/java/com/example/fitpassserver/domain/review/exception/ReviewErrorCode.java
  src/main/java/com/example/fitpassserver/domain/review/exception/ReviewException.java
  src/main/java/com/example/fitpassserver/domain/review/repsotiory/ReviewRepository.java
  src/main/java/com/example/fitpassserver/domain/review/service/ReviewService.java
Labels: ✨feature

#13 ✨ [Feat] 일반 유저 관련 기능
  build.gradle
  src/main/java/com/example/fitpassserver/domain/member/annotation/CurrentMember.java
  src/main/java/com/example/fitpassserver/domain/member/annotation/resolver/AuthenticatedMemberResolver.java
  src/main/java/com/example/fitpassserver/domain/member/controller/MemberController.java
  src/main/java/com/example/fitpassserver/domain/member/converter/MemberConverter.java
  src/main/java/com/example/fitpassserver/domain/member/dto/MemberRequestDTO.java
  src/main/java/com/example/fitpassserver/domain/member/dto/MemberResponseDTO.java
  src/main/java/com/example/fitpassserver/domain/member/entity/Member.java
  src/main/java/com/example/fitpassserver/domain/member/entity/MemberStatus.java
  src/main/java/com/example/fitpassserver/domain/member/exception/MemberErrorCode.java
  src/main/java/com/example/fitpassserver/domain/member/exception/MemberException.java
  src/main/java/com/example/fitpassserver/domain/member/principal/PrincipalDetails.java
  src/main/java/com/example/fitpassserver/domain/member/principal/PrincipalDetailsService.java
  src/main/java/com/example/fitpassserver/domain/member/repository/MemberRepository.java
  src/main/java/com/example/fitpassserver/domain/member/service/command/MemberCommandService.java
  src/main/java/com/example/fitpassserver/domain/member/service/command/MemberCommandServiceImpl.java
  src/main/java/com/example/fitpassserver/domain/member/service/query/MemberQueryService.java
  src/main/java/com/example/fitpassserver/domain/member/service/query/MemberQueryServiceImpl.java
  src/main/java/com/example/fitpassserver/domain/member/sms/controller/SmsController.java
  src/main/java/com/example/fitpassserver/domain/member/sms/dto/SmsRequestDTO.java
  src/main/java/com/example/fitpassserver/domain/member/sms/repositroy/SmsRepository.java
  src/main/java/com/example/fitpassserver/domain/member/sms/service/SmsService.java
  src/main/java/com/example/fitpassserver/domain/member/sms/service/SmsServiceImpl.java
  src/main/java/com/example/fitpassserver/domain/member/sms/util/SmsCertificationUtil.java
  src/main/java/com/example/fitpassserver/domain/member/validation/validator/AbstractValidator.java
  src/main/java/com/example/fitpassserver/domain/member/validation/validator/CheckLoginIdValidator.java
  src/main/java/com/example/fitpassserver/global/config/RedisConfig.java
  src/main/java/com/example/fitpassserver/global/config/SecurityConfig.java
  src/main/java/com/example/fitpassserver/global/jwt/exception/AuthException.java
  src/main/java/com/example/fitpassserver/global/jwt/exception/JwtErrorCode.java
  src/main/java/com/example/fitpassserver/global/jwt/filter/JwtFilter.java
  src/main/java/com/example/fitpassserver/global/jwt/handler/JwtAccessDeniedHandler.java
  src/main/java/com/example/fitpassserver/global/jwt/handler/JwtAuthenticationEntryPoint.java
  src/main/java/com/example/fitpassserver/global/jwt/util/JwtProvider.java
Labels: ✨feature

#19 ♻️ [Refactor] 일반 유저 기능
  src/main/java/com/example/fitpassserver/domain/member/annotation/CurrentMember.java
  src/main/java/com/example/fitpassserver/domain/member/annotation/resolver/CurrentMemberResolver.java
  src/main/java/com/example/fitpassserver/domain/member/dto/MemberRequestDTO.java
  src/main/java/com/example/fitpassserver/domain/plan/entity/Plan.java
  src/main/java/com/example/fitpassserver/global/config/WebConfig.java
  src/main/java/com/example/fitpassserver/global/jwt/util/JwtProvider.java
Labels: ♻️refactor

#20 ✨ [Feat] 패스 조회, 사용하기
  src/main/java/com/example/fitpassserver/domain/fitness/controller/MemberFitnessController.java
  src/main/java/com/example/fitpassserver/domain/fitness/converter/MemberFitnessConverter.java
  src/main/java/com/example/fitpassserver/domain/fitness/dto/response/MemberFitnessResDTO.java
  src/main/java/com/example/fitpassserver/domain/fitness/entity/MemberFitness.java
  src/main/java/com/example/fitpassserver/domain/fitness/entity/repository/MemberFitnessRepository.java
  src/main/java/com/example/fitpassserver/domain/fitness/exception/FitnessErrorCode.java
  src/main/java/com/example/fitpassserver/domain/fitness/exception/FitnessException.java
  src/main/java/com/example/fitpassserver/domain/fitness/repository/MemberFitnessRepository.java
  src/main/java/com/example/fitpassserver/domain/fitness/service/MemberFitnessService.java
Labels: ✨feature

#22 ✨ [Feat] 소셜 로그인 기능
  build.gradle
  src/main/java/com/example/fitpassserver/domain/member/controller/MemberController.java
  src/main/java/com/example/fitpassserver/domain/member/converter/MemberConverter.java
  src/main/java/com/example/fitpassserver/domain/member/dto/MemberRequestDTO.java
  src/main/java/com/example/fitpassserver/domain/member/entity/Member.java
  src/main/java/com/example/fitpassserver/domain/member/entity/Role.java
  src/main/java/com/example/fitpassserver/domain/member/principal/CustomOAuth2User.java
  src/main/java/com/example/fitpassserver/domain/member/principal/CustomOAuth2UserService.java
  src/main/java/com/example/fitpassserver/domain/member/repository/MemberRepository.java
  src/main/java/com/example/fitpassserver/domain/member/service/command/MemberCommandService.java
  src/main/java/com/example/fitpassserver/domain/member/service/command/MemberCommandServiceImpl.java
  src/main/java/com/example/fitpassserver/global/config/SecurityConfig.java
  src/main/java/com/example/fitpassserver/global/jwt/filter/JwtFilter.java
  src/main/java/com/example/fitpassserver/global/oauth/OAuthAttributes.java
  src/main/java/com/example/fitpassserver/global/oauth/handler/CustomOAuth2SuccessHandler.java
  src/main/java/com/example/fitpassserver/global/oauth/provider/GoogleOAuth2UserInfo.java
  src/main/java/com/example/fitpassserver/global/oauth/provider/NaverOAuth2UserInfo.java
  src/main/java/com/example/fitpassserver/global/oauth/provider/OAuth2UserInfo.java
Labels: ✨feature

#17 :sparkles: feat:피트니스 조회 관련 기능
  build.gradle
  src/main/java/com/example/fitpassserver/domain/fitness/controller/FitnessController.java
  src/main/java/com/example/fitpassserver/domain/fitness/controller/response/CursorPaginationResponse.java
  src/main/java/com/example/fitpassserver/domain/fitness/controller/response/FitnessDetailResponse.java
  src/main/java/com/example/fitpassserver/domain/fitness/controller/response/FitnessListResponse.java
  src/main/java/com/example/fitpassserver/domain/fitness/controller/response/FitnessRecommendResponse.java
  src/main/java/com/example/fitpassserver/domain/fitness/controller/response/FitnessSearchResponse.java
  src/main/java/com/example/fitpassserver/domain/fitness/entity/Fitness.java
  src/main/java/com/example/fitpassserver/domain/fitness/repository/FitnessRepository.java
  src/main/java/com/example/fitpassserver/domain/fitness/service/FitnessDetailService.java
  src/main/java/com/example/fitpassserver/domain/fitness/service/FitnessListService.java
  src/main/java/com/example/fitpassserver/domain/fitness/service/FitnessRecommendService.java
  src/main/java/com/example/fitpassserver/domain/fitness/service/FitnessSearchService.java
  src/main/java/com/example/fitpassserver/domain/fitness/util/DistanceCalculator.java
Labels: ✨feature

#30 :memo: [Refactor] import 폴더 네임 수정
  src/main/java/com/example/fitpassserver/domain/fitness/controller/FitnessController.java
  src/main/java/com/example/fitpassserver/domain/fitness/controller/response/CursorPaginationResponse.java
  src/main/java/com/example/fitpassserver/domain/fitness/controller/response/FitnessDetailResponse.java
  src/main/java/com/example/fitpassserver/domain/fitness/controller/response/FitnessListResponse.java
  src/main/java/com/example/fitpassserver/domain/fitness/controller/response/FitnessRecommendResponse.java
  src/main/java/com/example/fitpassserver/domain/fitness/controller/response/FitnessSearchResponse.java
  src/main/java/com/example/fitpassserver/domain/fitness/converter/MemberFitnessConverter.java
  src/main/java/com/example/fitpassserver/domain/fitness/dto/response/MemberFitnessResDTO.java
  src/main/java/com/example/fitpassserver/domain/fitness/exception/FitnessErrorCode.java
  src/main/java/com/example/fitpassserver/domain/fitness/repository/FitnessRepository.java
  src/main/java/com/example/fitpassserver/domain/fitness/repository/MemberFitnessRepository.java
  src/main/java/com/example/fitpassserver/domain/fitness/service/FitnessDetailService.java
  src/main/java/com/example/fitpassserver/domain/fitness/service/FitnessListService.java
  src/main/java/com/example/fitpassserver/domain/fitness/service/FitnessRecommendService.java
  src/main/java/com/example/fitpassserver/domain/fitness/service/FitnessSearchService.java
  src/main/java/com/example/fitpassserver/domain/fitness/service/MemberFitnessService.java
  src/main/java/com/example/fitpassserver/domain/fitness/util/DistanceCalculator.java
Labels: ♻️refactor

#28 ✨ [Feat] 사용자 현재 위치 설정
  src/main/java/com/example/fitpassserver/domain/member/controller/MemberController.java
  src/main/java/com/example/fitpassserver/domain/member/dto/MemberRequestDTO.java
  src/main/java/com/example/fitpassserver/domain/member/entity/Member.java
  src/main/java/com/example/fitpassserver/domain/member/service/command/MemberCommandService.java
  src/main/java/com/example/fitpassserver/domain/member/service/command/MemberCommandServiceImpl.java
Labels: ✨feature

#25 ♻️[Refactor] 리뷰, 패스 Swagger 및 인가 적용
  src/main/java/com/example/fitpassserver/domain/fitness/dto/response/MemberFitnessResDTO.java
  src/main/java/com/example/fitpassserver/domain/review/controller/ReviewController.java
  src/main/java/com/example/fitpassserver/domain/review/dto/request/ReviewReqDTO.java
  src/main/java/com/example/fitpassserver/domain/review/service/ReviewService.java
Labels: ♻️refactor

#24 ✨[Feat] 피트니스 패스 구매 API 구현
  src/main/java/com/example/fitpassserver/domain/coin/converter/CoinUsageHistoryConverter.java
  src/main/java/com/example/fitpassserver/domain/coin/entity/Coin.java
  src/main/java/com/example/fitpassserver/domain/coin/repository/CoinRepository.java
  src/main/java/com/example/fitpassserver/domain/coin/repository/CoinUsageHistoryRepository.java
  src/main/java/com/example/fitpassserver/domain/coin/service/command/CoinUsageHistoryService.java
  src/main/java/com/example/fitpassserver/domain/coin/service/command/CoinUsageHistoryServiceImpl.java
  src/main/java/com/example/fitpassserver/domain/fitness/controller/MemberFitnessController.java
  src/main/java/com/example/fitpassserver/domain/fitness/converter/MemberFitnessConverter.java
  src/main/java/com/example/fitpassserver/domain/fitness/dto/MemberFitnessRequestDTO.java
  src/main/java/com/example/fitpassserver/domain/fitness/dto/MemberFitnessResponseDTO.java
  src/main/java/com/example/fitpassserver/domain/fitness/exception/MemberFitnessErrorCode.java
  src/main/java/com/example/fitpassserver/domain/fitness/exception/MemberFitnessException.java
  src/main/java/com/example/fitpassserver/domain/fitness/repository/FitnessRepository.java
  src/main/java/com/example/fitpassserver/domain/fitness/repository/MemberFitnessRepository.java
  src/main/java/com/example/fitpassserver/domain/fitness/service/command/MemberFitnessCommandService.java
  src/main/java/com/example/fitpassserver/domain/fitness/service/command/MemberFitnessCommandServiceImpl.java
  src/main/java/com/example/fitpassserver/domain/fitnessPaymentHistory/converter/FitnessPaymentHistoryConverter.java
  src/main/java/com/example/fitpassserver/domain/fitnessPaymentHistory/repository/FitnessPaymentHistoryRepository.java
Labels: ✨feature

#39 ✨[Feat] 피트니스 구매 취소 API 구현
  src/main/java/com/example/fitpassserver/domain/coin/entity/Coin.java
  src/main/java/com/example/fitpassserver/domain/coin/exception/CoinUsageHistoryErrorCode.java
  src/main/java/com/example/fitpassserver/domain/coin/exception/CoinUsageHistoryException.java
  src/main/java/com/example/fitpassserver/domain/coin/repository/CoinRepository.java
  src/main/java/com/example/fitpassserver/domain/coin/repository/CoinUsageHistoryRepository.java
  src/main/java/com/example/fitpassserver/domain/fitness/controller/MemberFitnessController.java
  src/main/java/com/example/fitpassserver/domain/fitness/converter/MemberFitnessConverter.java
  src/main/java/com/example/fitpassserver/domain/fitness/dto/MemberFitnessRequestDTO.java
  src/main/java/com/example/fitpassserver/domain/fitness/dto/MemberFitnessResponseDTO.java
  src/main/java/com/example/fitpassserver/domain/fitness/exception/MemberFitnessErrorCode.java
  src/main/java/com/example/fitpassserver/domain/fitness/service/command/MemberFitnessCommandService.java
  src/main/java/com/example/fitpassserver/domain/fitness/service/command/MemberFitnessCommandServiceImpl.java
  src/main/java/com/example/fitpassserver/domain/fitnessPaymentHistory/exception/FitnessPaymentHistoryErrorCode.java
  src/main/java/com/example/fitpassserver/domain/fitnessPaymentHistory/exception/FitnessPaymentHistoryException.java
  src/main/java/com/example/fitpassserver/domain/fitnessPaymentHistory/repository/FitnessPaymentHistoryRepository.java
Labels: ✨feature

#41 :sparkles: [Feat] 프로필 이미지 구현
  build.gradle
  src/main/java/com/example/fitpassserver/domain/plan/repository/PlanRepository.java
  src/main/java/com/example/fitpassserver/domain/profile/controller/ProfileController.java
  src/main/java/com/example/fitpassserver/domain/profile/dto/ProfileRequestDTO.java
  src/main/java/com/example/fitpassserver/domain/profile/dto/ProfileResponseDTO.java
  src/main/java/com/example/fitpassserver/domain/profile/entity/Profile.java
  src/main/java/com/example/fitpassserver/domain/profile/exception/ProfileErrorCode.java
  src/main/java/com/example/fitpassserver/domain/profile/exception/ProfileException.java
  src/main/java/com/example/fitpassserver/domain/profile/repositroy/ProfileRepository.java
  src/main/java/com/example/fitpassserver/domain/profile/service/ProfileService.java
  src/main/java/com/example/fitpassserver/global/aws/s3/controller/S3Controller.java
  src/main/java/com/example/fitpassserver/global/aws/s3/dto/S3UrlResponseDTO.java
  src/main/java/com/example/fitpassserver/global/aws/s3/exception/S3ErrorCode.java
  src/main/java/com/example/fitpassserver/global/aws/s3/exception/S3Exception.java
  src/main/java/com/example/fitpassserver/global/aws/s3/service/S3Service.java
  src/main/java/com/example/fitpassserver/global/aws/s3/util/S3Uploader.java
  src/main/java/com/example/fitpassserver/global/config/S3Config.java
Labels: ✨feature

#43 ♻️ [Refactor] 리뷰 조회 시 본인 리뷰 확인
  src/main/java/com/example/fitpassserver/domain/fitness/exception/FitnessErrorCode.java
  src/main/java/com/example/fitpassserver/domain/review/controller/ReviewController.java
  src/main/java/com/example/fitpassserver/domain/review/converter/ReviewConverter.java
  src/main/java/com/example/fitpassserver/domain/review/dto/response/ReviewResDTO.java
  src/main/java/com/example/fitpassserver/domain/review/service/ReviewService.java
Labels: ♻️refactor

#44 ✨ [Feat] 정기 구독 결제 구현
  src/main/java/com/example/fitpassserver/domain/coin/entity/Coin.java
  src/main/java/com/example/fitpassserver/domain/coin/entity/CoinType.java
  src/main/java/com/example/fitpassserver/domain/coin/service/CoinService.java
  src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/controller/CoinPaymentController.java
  src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/controller/PlanPaymentController.java
  src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/CoinPaymentHistoryService.java
  src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/KakaoPaymentService.java
  src/main/java/com/example/fitpassserver/domain/member/entity/Member.java
  src/main/java/com/example/fitpassserver/domain/plan/controller/PlanPaymentController.java
  src/main/java/com/example/fitpassserver/domain/plan/dto/request/SubscriptionCancelRequestDTO.java
  src/main/java/com/example/fitpassserver/domain/plan/dto/request/SubscriptionRequestDTO.java
  src/main/java/com/example/fitpassserver/domain/plan/dto/response/FirstSubscriptionResponseDTO.java
  src/main/java/com/example/fitpassserver/domain/plan/dto/response/KakaoCancelResponseDTO.java
  src/main/java/com/example/fitpassserver/domain/plan/dto/response/PlanSubscriptionResponseDTO.java
  src/main/java/com/example/fitpassserver/domain/plan/dto/response/SubscriptionCancelResponseDTO.java
  src/main/java/com/example/fitpassserver/domain/plan/dto/response/SubscriptionResponseDTO.java
  src/main/java/com/example/fitpassserver/domain/plan/entity/Plan.java
  src/main/java/com/example/fitpassserver/domain/plan/entity/PlanName.java
  src/main/java/com/example/fitpassserver/domain/plan/entity/PlanType.java
  src/main/java/com/example/fitpassserver/domain/plan/exception/PlanErrorCode.java
  src/main/java/com/example/fitpassserver/domain/plan/exception/PlanException.java
  src/main/java/com/example/fitpassserver/domain/plan/repository/PlanRepository.java
  src/main/java/com/example/fitpassserver/domain/plan/service/PlanService.java
Labels: ✨feature

#35 🚀 [Chore] CI/CD 추가
  .github/workflows/deploy.yml
  .gitignore
  Dockerfile
  build.gradle
  src/test/java/com/example/fitpassserver/FitpassServerApplicationTests.java
Labels: 🚀chore

#47 :bug: [Bug] 프로필이미지 변수 불일치 해결
  src/main/java/com/example/fitpassserver/domain/profile/dto/ProfileResponseDTO.java
  src/main/java/com/example/fitpassserver/domain/profile/service/ProfileService.java
Labels: 🐛bug

#51 :recycle: [Refactor] S3 upload 변경
  src/main/java/com/example/fitpassserver/domain/member/service/command/MemberCommandServiceImpl.java
  src/main/java/com/example/fitpassserver/domain/profile/controller/ProfileController.java
  src/main/java/com/example/fitpassserver/domain/profile/dto/ProfileRequestDTO.java
  src/main/java/com/example/fitpassserver/domain/profile/dto/ProfileResponseDTO.java
  src/main/java/com/example/fitpassserver/domain/profile/entity/Profile.java
  src/main/java/com/example/fitpassserver/domain/profile/exception/ProfileErrorCode.java
  src/main/java/com/example/fitpassserver/domain/profile/service/ProfileService.java
  src/main/java/com/example/fitpassserver/global/aws/s3/dto/S3UrlResponseDTO.java
  src/main/java/com/example/fitpassserver/global/aws/s3/service/S3Service.java
  src/main/java/com/example/fitpassserver/global/aws/s3/util/S3Uploader.java
Labels: ♻️refactor

#52 ✨ [Feat] 결제 시 문자 알림 기능
  src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/controller/CoinPaymentController.java
  src/main/java/com/example/fitpassserver/domain/fitness/service/command/MemberFitnessCommandServiceImpl.java
  src/main/java/com/example/fitpassserver/domain/member/sms/util/SmsCertificationUtil.java
  src/main/java/com/example/fitpassserver/domain/plan/controller/PlanPaymentController.java
Labels: ✨feature

#66 :recycle: [Refactor} status에 @Builder.Default 추가
  src/main/java/com/example/fitpassserver/domain/member/entity/Member.java
Labels: ♻️refactor

#58 ♻️ refactor(memberfitness) 패스 상태 DONE 스케쥴러
  src/main/java/com/example/fitpassserver/FitpassServerApplication.java
  src/main/java/com/example/fitpassserver/domain/fitness/entity/MemberFitness.java
  src/main/java/com/example/fitpassserver/domain/fitness/repository/MemberFitnessRepository.java
  src/main/java/com/example/fitpassserver/domain/fitness/util/PassStatusScheduler.java
Labels: ♻️refactor

#73 :recycle: [Refactor] 유효성 검사 추가
  src/main/java/com/example/fitpassserver/domain/member/service/command/MemberCommandServiceImpl.java
Labels: ♻️refactor

#76 ✨ [Feat] 결제 내역 조회 API 구현
  src/main/java/com/example/fitpassserver/domain/coin/exception/CoinErrorCode.java
  src/main/java/com/example/fitpassserver/domain/coin/repository/CoinRepository.java
  src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/controller/CoinPaymentController.java
  src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/dto/response/CoinPaymentHistoryResponseListDTO.java
  src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/entity/CoinPaymentHistory.java
  src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/CoinPaymentHistoryService.java
  src/main/java/com/example/fitpassserver/domain/fitness/service/command/MemberFitnessCommandServiceImpl.java
  src/main/java/com/example/fitpassserver/domain/plan/controller/PlanPaymentController.java
Labels: ✨feature

#75 :sparkles: [Feat} https 적용 임의 컨트롤러 추가
  src/main/java/com/example/fitpassserver/domain/member/sms/controller/SmsController.java
Labels: ✨feature

#72 ♻️ [Refactor] OAuth 토큰 발급 방식 헤더로 변경
  src/main/java/com/example/fitpassserver/global/oauth/handler/CustomOAuth2SuccessHandler.java
Labels: ♻️refactor

#80 ✨feat(plan) 금액 부족 시 문자 발송
  src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/KakaoPaymentService.java
  src/main/java/com/example/fitpassserver/domain/member/sms/util/SmsCertificationUtil.java
Labels: ✨feature

#89 🐛 [Fix] 결제 내역 응답 필드 수정
  src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/dto/response/CoinPaymentHistoryResponseListDTO.java
  src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/CoinPaymentHistoryService.java
Labels: 🐛bug

#100 ✨ [Feat] 피트니스 패스 구매 페이지 API 구현
  src/main/java/com/example/fitpassserver/domain/fitness/controller/FitnessController.java
  src/main/java/com/example/fitpassserver/domain/fitness/controller/response/FitnessPaymentResponse.java
  src/main/java/com/example/fitpassserver/domain/fitness/service/FitnessPaymentService.java
Labels: ✨feature

#104 🐛 [Fix] 구독 중 필드 값 수정
  src/main/java/com/example/fitpassserver/domain/coin/repository/CoinRepository.java
  src/main/java/com/example/fitpassserver/domain/coinPaymentHistory/service/CoinPaymentHistoryService.java
Labels: 🐛bug

#102 ✨ [Feat] 어드민 기본 설정
  src/main/java/com/example/fitpassserver/admin/dashboard/controller/DashboardAdminController.java
  src/main/java/com/example/fitpassserver/admin/dashboard/service/DashboardAdminService.java
  src/main/java/com/example/fitpassserver/admin/dashboard/service/DashboardAdminServiceImpl.java
  src/main/java/com/example/fitpassserver/admin/fitness/controller/FitnessAdminController.java
  src/main/java/com/example/fitpassserver/admin/fitness/service/FitnessAdminService.java
  src/main/java/com/example/fitpassserver/admin/fitness/service/FitnessAdminServiceImpl.java
  src/main/java/com/example/fitpassserver/admin/member/controller/MemberAdminController.java
  src/main/java/com/example/fitpassserver/admin/member/service/MemberAdminService.java
  src/main/java/com/example/fitpassserver/admin/member/service/MemberAdminServiceImpl.java
  src/main/java/com/example/fitpassserver/admin/notice/controller/NoticeAdminController.java
  src/main/java/com/example/fitpassserver/admin/notice/service/NoticeAdminService.java
  src/main/java/com/example/fitpassserver/admin/notice/service/NoticeAdminServiceImpl.java
  src/main/java/com/example/fitpassserver/admin/payment/controller/PaymentAdminController.java
  src/main/java/com/example/fitpassserver/admin/payment/service/PaymentAdminService.java
  src/main/java/com/example/fitpassserver/admin/payment/service/PaymentAdminServiceImpl.java
  src/main/java/com/example/fitpassserver/global/config/SecurityConfig.java
Labels: ✨feature

#109 ♻️ refactor(memberfitness) 보유 패스 조회 시설 정보 추가
  src/main/java/com/example/fitpassserver/domain/fitness/converter/MemberFitnessConverter.java
  src/main/java/com/example/fitpassserver/domain/fitness/dto/response/MemberFitnessResDTO.java
  src/main/java/com/example/fitpassserver/domain/fitness/service/MemberFitnessService.java
Labels: ♻️refactor
